version: '2.2'

services:
  mytb:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "80:9090"
      - "1883:1883"
      - "5683:5683/udp"
    volumes: 
      - data:/data
      - logs:/var/log/thingsboard

volumes:
  data:
  logs: